public enum TipologieCrimine
{
	RAPINA,
	RAPINA_A_MANO_ARMATA,
	SFRUTTAMENTO_MINORILE,
	OMICIDIO_INTENZIONALE,
	DISTRUZIONE_DI_PROPRIETA,
	DISTRUZIONE_DI_METODI,
	INCENDIO,
	FURTO_INFORMATICO,
	TRAFFICO_DI_ORGANI,
	CODICE_NON_INDENTATO,
	EVASIONE_FISCALE,
	INSURREZIONE,
	RISSA_CON_BAMBINI
}
